# ===== Application Under Test (AUT) =====
app.url=https://vanphongdientu.utc.edu.vn/Login?r=https%3A%2F%2Fvanphongdientu.utc.edu.vn%2F
home.url=https://vanphongdientu.utc.edu.vn/

# ===== Browser =====
browser=chrome
headless=false
implicit.wait=10
explicit.wait=15
page.load.timeout=30

# ===== Credentials (happy-path) =====
valid.username=huongnt
valid.password=123456@utc

# ===== Test data file =====
testdata.file=Test_Cases_Dang_Nhap.xlsx
testdata.sheet=Test Cases Đăng Nhập
